version: "3"
services:

  api:
    build:
      dockerfile: ./devtools/docker/Dockerfile.local
      context: ./api
    image: todo-application-api:latest
    restart: always
    ports:
      - ${APP_PORT:-9999}:${APP_PORT:-9999}
    volumes:
      - ./api:/app
    environment:
      TZ: Asia/Bangkok
      APP_ENV: ${APP_ENV:-local}
      APP_PORT: ${APP_PORT:-9999}
      DATABASE_HOST: ${DB_HOST:-db}
      DATABASE_PORT: ${DB_PORT:-5432}
      DATABASE_NAME: ${DB_NAME:-todo}
      DATABASE_USER: ${DB_USER:-postgres}
      DATABASE_PASSWORD: ${DB_PASSWORD:-postgres}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  db_data:

networks:
  default:
    name: development