version: "3"
services:

  api:
    build:
      dockerfile: ./devtools/docker/Dockerfile.local
      context: ./api
    image: todo-application-api:latest
    restart: always
    volumes:
      - ./api:/app
    environment:
      APP_ENV: local
      TZ: Asia/Bangkok
